version: "3.8"

services:
  tiktok-bot:
    build: .
    container_name: tiktok-downloader-bot
    environment:
      - TOKEN=${TOKEN}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('https://api.telegram.org/bot${TOKEN}/getMe')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
